# Generated by Django 3.2.8 on 2021-11-18 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='data_Humidity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('value', models.FloatField(blank=True, null=True)),
                ('signal', models.CharField(max_length=200)),
                ('sensor_id', models.IntegerField(blank=True, null=True)),
                ('variable_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'HUMIDITY',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='data_LeafWetness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('value', models.FloatField(blank=True, null=True)),
                ('signal', models.CharField(max_length=200)),
                ('sensor_id', models.IntegerField(blank=True, null=True)),
                ('variable_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'LEAF_WETNESS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='data_Pressure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('value', models.FloatField(blank=True, null=True)),
                ('signal', models.CharField(max_length=200)),
                ('sensor_id', models.IntegerField(blank=True, null=True)),
                ('variable_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'PRESSURE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='data_Rainfall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('value', models.FloatField(blank=True, null=True)),
                ('signal', models.CharField(max_length=200)),
                ('sensor_id', models.IntegerField(blank=True, null=True)),
                ('variable_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'RAINFALL',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='data_Resistance',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('value', models.FloatField(blank=True, null=True)),
                ('signal', models.CharField(max_length=200)),
                ('sensor_id', models.IntegerField(blank=True, null=True)),
                ('variable_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'RESISTANCE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='data_Swp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('value', models.FloatField(blank=True, null=True)),
                ('signal', models.CharField(max_length=200)),
                ('sensor_id', models.IntegerField(blank=True, null=True)),
                ('variable_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'SWP',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='data_Temperature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('value', models.FloatField(blank=True, null=True)),
                ('signal', models.CharField(max_length=200)),
                ('sensor_id', models.IntegerField(blank=True, null=True)),
                ('variable_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'TEMPERATURE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='data_WindDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('value', models.FloatField(blank=True, null=True)),
                ('signal', models.CharField(max_length=200)),
                ('sensor_id', models.IntegerField(blank=True, null=True)),
                ('variable_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'WIND_DIRECTION',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='data_WindGust',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('value', models.FloatField(blank=True, null=True)),
                ('signal', models.CharField(max_length=200)),
                ('sensor_id', models.IntegerField(blank=True, null=True)),
                ('variable_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'WIND_GUST',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='data_WindSpeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('value', models.FloatField(blank=True, null=True)),
                ('signal', models.CharField(max_length=200)),
                ('sensor_id', models.IntegerField(blank=True, null=True)),
                ('variable_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'WIND_SPEED',
                'managed': False,
            },
        ),
    ]
