# Generated by Django 4.0.4 on 2022-05-26 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_datacleverfarm_dataekotechnika_dataemsbrno_datanone_datatomst_datavrty'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataNone',
        ),
    ]
