# Generated by Django 3.2.4 on 2021-07-28 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='API',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_id', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceActions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('investigator', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=1000)),
                ('identification_code', models.CharField(max_length=255)),
                ('license', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sensors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.IntegerField()),
                ('sensor_name', models.CharField(max_length=255)),
                ('serial_number', models.CharField(max_length=255)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('elevation', models.FloatField()),
                ('price', models.FloatField()),
                ('warranty', models.IntegerField()),
                ('connection_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.api')),
            ],
        ),
        migrations.CreateModel(
            name='SensorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_type_id', models.IntegerField()),
                ('company', models.CharField(max_length=255)),
                ('calibration_interval', models.IntegerField()),
                ('time_step', models.IntegerField()),
                ('technician_czu', models.BooleanField()),
                ('technician_company', models.BooleanField()),
                ('note_link', models.CharField(max_length=1000)),
                ('tech_doc_link', models.CharField(max_length=1000)),
                ('photos_link', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Variables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('note', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SensorVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chip_id', models.CharField(max_length=255)),
                ('limit_value_min', models.FloatField()),
                ('limit_value_max', models.FloatField()),
                ('unit', models.CharField(max_length=255)),
                ('vertical_floor', models.CharField(max_length=255)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.project')),
                ('sensor_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='dashboard.sensors')),
                ('variable_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.variables')),
            ],
        ),
        migrations.CreateModel(
            name='SensorsGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('connection_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.api')),
                ('sensor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.sensors')),
            ],
        ),
        migrations.AddField(
            model_name='sensors',
            name='sensor_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.sensortype'),
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
                ('user', models.CharField(max_length=255)),
                ('action', models.CharField(max_length=255)),
                ('note', models.TextField()),
                ('sensor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.sensors')),
            ],
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now=True)),
                ('start_time', models.TimeField(auto_now=True)),
                ('end_date', models.DateField(auto_now_add=True)),
                ('end_time', models.TimeField(auto_now_add=True)),
                ('condition', models.CharField(max_length=255)),
                ('note', models.TextField()),
                ('sensor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.sensors')),
            ],
        ),
    ]
