# Generated by Django 2.2.20 on 2021-06-14 09:45

import django.contrib.gis.db.models.fields
from django.db import migrations, models
from django.contrib.postgres.operations import CreateExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        CreateExtension('postgis'),
        migrations.CreateModel(
            name='Sensors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.CharField(max_length=255)),
                ('sensor_name', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('measured_quantity', models.CharField(max_length=255)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('calibration_interval', models.DateField()),
                ('calibrated_on', models.DateField(auto_now_add=True)),
                ('units', models.CharField(max_length=50)),
                ('limit_min', models.FloatField()),
                ('limit_max', models.FloatField()),
            ],
        ),
    ]
