# Generated by Django 3.2.4 on 2021-08-23 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('connection_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='dashboard.api')),
            ],
        ),
        migrations.RemoveField(
            model_name='condition',
            name='sensor_id',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='sensor_id',
        ),
        migrations.RemoveField(
            model_name='sensors',
            name='connection_id',
        ),
        migrations.RemoveField(
            model_name='sensors',
            name='sensor_id',
        ),
        migrations.RemoveField(
            model_name='sensors',
            name='sensor_type_id',
        ),
        migrations.RemoveField(
            model_name='sensorsgroup',
            name='connection_id',
        ),
        migrations.RemoveField(
            model_name='sensorsgroup',
            name='sensor_id',
        ),
        migrations.RemoveField(
            model_name='sensorvariable',
            name='project_id',
        ),
        migrations.RemoveField(
            model_name='sensorvariable',
            name='sensor_id',
        ),
        migrations.RemoveField(
            model_name='sensorvariable',
            name='variable_id',
        ),
        migrations.AddField(
            model_name='condition',
            name='sensor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.sensors'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='sensor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.sensors'),
        ),
        migrations.AddField(
            model_name='sensors',
            name='connection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='dashboard.api'),
        ),
        migrations.AddField(
            model_name='sensors',
            name='sensor_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='dashboard.sensortype'),
        ),
        migrations.AddField(
            model_name='sensorsgroup',
            name='connection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='dashboard.api'),
        ),
        migrations.AddField(
            model_name='sensorsgroup',
            name='sensor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.sensors'),
        ),
        migrations.AddField(
            model_name='sensorvariable',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='dashboard.project'),
        ),
        migrations.AddField(
            model_name='sensorvariable',
            name='sensor',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.sensors'),
        ),
        migrations.AddField(
            model_name='sensorvariable',
            name='variable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.variables'),
        ),
        migrations.AlterField(
            model_name='variables',
            name='variable_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='SensorGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='dashboard.group')),
                ('sensor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.sensors')),
            ],
        ),
    ]
