# Generated by Django 3.2.4 on 2021-08-26 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210823_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensors',
            name='note',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='sensors',
            name='spatial_precision',
            field=models.CharField(default='blank', max_length=255),
        ),
    ]
