# Generated by Django 3.2.4 on 2021-08-26 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20210826_0747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensortype',
            name='technician_company',
        ),
        migrations.RemoveField(
            model_name='sensortype',
            name='technician_czu',
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('technician_czu', models.BooleanField()),
                ('technician_company', models.BooleanField()),
                ('sensor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.sensors')),
                ('sensor_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.sensortype')),
            ],
        ),
    ]
