# Generated by Django 3.2.4 on 2021-08-27 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20210826_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='sensor_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensor_type', to='dashboard.sensortype'),
        ),
        migrations.AlterField(
            model_name='sensortype',
            name='sensor_type_id',
            field=models.CharField(max_length=255),
        ),
    ]
