# Generated by Django 3.2.4 on 2021-09-05 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20210827_0843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensors',
            name='warranty',
        ),
    ]
