# Generated by Django 3.2.4 on 2021-09-05 09:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_remove_sensors_warranty'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensors',
            name='warranty',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
