# Generated by Django 3.2.4 on 2021-09-13 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_sensors_warranty'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorvariable',
            name='note',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.people'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.people'),
        ),
    ]
