# Generated by Django 3.2.4 on 2021-09-14 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20210913_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='link',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='condition',
            name='note',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='note',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='identification_code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='license',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='sensors',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sensortype',
            name='note_link',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='sensortype',
            name='photos_link',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='sensortype',
            name='tech_doc_link',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='sensorvariable',
            name='chip_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='variables',
            name='note',
            field=models.TextField(null=True),
        ),
    ]
