# Generated by Django 3.2.4 on 2021-08-01 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_name', models.CharField(max_length=255)),
                ('year', models.IntegerField(default=2021)),
                ('month', models.SmallIntegerField(default=8)),
                ('feature', models.CharField(max_length=255)),
                ('mean', models.FloatField()),
                ('min', models.FloatField()),
                ('max', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Wns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('value', models.FloatField(null=True)),
                ('signal', models.CharField(max_length=200)),
                ('sensor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.sensors')),
                ('variable_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.variables')),
            ],
            options={
                'db_table': 'WIND_SPEED',
            },
        ),
        migrations.CreateModel(
            name='Wng',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('value', models.FloatField(null=True)),
                ('signal', models.CharField(max_length=200)),
                ('sensor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.sensors')),
                ('variable_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.variables')),
            ],
            options={
                'db_table': 'WIND_GUST',
            },
        ),
        migrations.CreateModel(
            name='Wnd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('value', models.FloatField(null=True)),
                ('signal', models.CharField(max_length=200)),
                ('sensor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.sensors')),
                ('variable_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.variables')),
            ],
            options={
                'db_table': 'WIND_DIRECTION',
            },
        ),
        migrations.CreateModel(
            name='Tmp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('value', models.FloatField(null=True)),
                ('signal', models.CharField(max_length=200)),
                ('sensor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.sensors')),
                ('variable_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.variables')),
            ],
            options={
                'db_table': 'TEMPERATURE',
            },
        ),
        migrations.CreateModel(
            name='Swp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('value', models.FloatField(null=True)),
                ('signal', models.CharField(max_length=200)),
                ('sensor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.sensors')),
                ('variable_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.variables')),
            ],
            options={
                'db_table': 'SWP',
            },
        ),
        migrations.CreateModel(
            name='Rnf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('value', models.FloatField(null=True)),
                ('signal', models.CharField(max_length=200)),
                ('sensor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.sensors')),
                ('variable_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.variables')),
            ],
            options={
                'db_table': 'RAINFALL',
            },
        ),
        migrations.CreateModel(
            name='Prs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('value', models.FloatField(null=True)),
                ('signal', models.CharField(max_length=200)),
                ('sensor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.sensors')),
                ('variable_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.variables')),
            ],
            options={
                'db_table': 'PRESSURE',
            },
        ),
        migrations.CreateModel(
            name='Lfw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('value', models.FloatField(null=True)),
                ('signal', models.CharField(max_length=200)),
                ('sensor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.sensors')),
                ('variable_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.variables')),
            ],
            options={
                'db_table': 'LEAF_WETNESS',
            },
        ),
        migrations.CreateModel(
            name='Hum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('value', models.FloatField(null=True)),
                ('signal', models.CharField(max_length=200)),
                ('sensor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.sensors')),
                ('variable_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.variables')),
            ],
            options={
                'db_table': 'HUMIDITY',
            },
        ),
    ]
