# Generated by Django 3.2.4 on 2021-08-23 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hum',
            old_name='sensor_id',
            new_name='sensor',
        ),
        migrations.RenameField(
            model_name='hum',
            old_name='variable_id',
            new_name='variable',
        ),
        migrations.RenameField(
            model_name='lfw',
            old_name='sensor_id',
            new_name='sensor',
        ),
        migrations.RenameField(
            model_name='lfw',
            old_name='variable_id',
            new_name='variable',
        ),
        migrations.RenameField(
            model_name='prs',
            old_name='sensor_id',
            new_name='sensor',
        ),
        migrations.RenameField(
            model_name='prs',
            old_name='variable_id',
            new_name='variable',
        ),
        migrations.RenameField(
            model_name='rnf',
            old_name='sensor_id',
            new_name='sensor',
        ),
        migrations.RenameField(
            model_name='rnf',
            old_name='variable_id',
            new_name='variable',
        ),
        migrations.RenameField(
            model_name='swp',
            old_name='sensor_id',
            new_name='sensor',
        ),
        migrations.RenameField(
            model_name='swp',
            old_name='variable_id',
            new_name='variable',
        ),
        migrations.RenameField(
            model_name='tmp',
            old_name='sensor_id',
            new_name='sensor',
        ),
        migrations.RenameField(
            model_name='tmp',
            old_name='variable_id',
            new_name='variable',
        ),
        migrations.RenameField(
            model_name='wnd',
            old_name='sensor_id',
            new_name='sensor',
        ),
        migrations.RenameField(
            model_name='wnd',
            old_name='variable_id',
            new_name='variable',
        ),
        migrations.RenameField(
            model_name='wng',
            old_name='sensor_id',
            new_name='sensor',
        ),
        migrations.RenameField(
            model_name='wng',
            old_name='variable_id',
            new_name='variable',
        ),
        migrations.RenameField(
            model_name='wns',
            old_name='sensor_id',
            new_name='sensor',
        ),
        migrations.RenameField(
            model_name='wns',
            old_name='variable_id',
            new_name='variable',
        ),
    ]
