# Generated by Django 3.2.4 on 2021-08-23 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210823_0909'),
        ('query', '0002_auto_20210823_0909'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('value', models.FloatField(null=True)),
                ('signal', models.CharField(max_length=200)),
                ('sensor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.sensors')),
                ('variable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.variables')),
            ],
            options={
                'db_table': 'RESISTANCE',
            },
        ),
    ]
