# Generated by Django 3.2.8 on 2021-10-11 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Humidity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('value', models.FloatField(blank=True, null=True)),
                ('signal', models.CharField(max_length=200)),
                ('sensor_id', models.IntegerField(blank=True, null=True)),
                ('variable_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'HUMIDITY',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LeafWetness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('value', models.FloatField(blank=True, null=True)),
                ('signal', models.CharField(max_length=200)),
                ('sensor_id', models.IntegerField(blank=True, null=True)),
                ('variable_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'LEAF_WETNESS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pressure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('value', models.FloatField(blank=True, null=True)),
                ('signal', models.CharField(max_length=200)),
                ('sensor_id', models.IntegerField(blank=True, null=True)),
                ('variable_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'PRESSURE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rainfall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('value', models.FloatField(blank=True, null=True)),
                ('signal', models.CharField(max_length=200)),
                ('sensor_id', models.IntegerField(blank=True, null=True)),
                ('variable_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'RAINFALL',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Resistance',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('value', models.FloatField(blank=True, null=True)),
                ('signal', models.CharField(max_length=200)),
                ('sensor_id', models.IntegerField(blank=True, null=True)),
                ('variable_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'RESISTANCE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Swp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('value', models.FloatField(blank=True, null=True)),
                ('signal', models.CharField(max_length=200)),
                ('sensor_id', models.IntegerField(blank=True, null=True)),
                ('variable_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'SWP',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('value', models.FloatField(blank=True, null=True)),
                ('signal', models.CharField(max_length=200)),
                ('sensor_id', models.IntegerField(blank=True, null=True)),
                ('variable_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'TEMPERATURE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WindDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('value', models.FloatField(blank=True, null=True)),
                ('signal', models.CharField(max_length=200)),
                ('sensor_id', models.IntegerField(blank=True, null=True)),
                ('variable_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'WIND_DIRECTION',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WindGust',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('value', models.FloatField(blank=True, null=True)),
                ('signal', models.CharField(max_length=200)),
                ('sensor_id', models.IntegerField(blank=True, null=True)),
                ('variable_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'WIND_GUST',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WindSpeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('value', models.FloatField(blank=True, null=True)),
                ('signal', models.CharField(max_length=200)),
                ('sensor_id', models.IntegerField(blank=True, null=True)),
                ('variable_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'WIND_SPEED',
                'managed': False,
            },
        ),
    ]
